### ISSUE TITLE
Browser Option?

### ISSUE THREAD

**Issue by twoxfh** [hildjj/quence#15]
Any thoughts on making this library browser compatible? There are some pretty useful language features for drawing diagrams which are not covered by other libraries.

**Comment by hildjj** [comment]
That might be fun to do.  I'm thinking a canvas output style, and then browserify + webpack or rollup.  How much of that should go into the library, vs a separate package that does the web bits?

**Comment by twoxfh** [comment]
Was thinking the whole thing would be abstracted and you could take the svg output and send it to a div which can have an svg viewer attached. I did find mscgeny, another project which is also web focused, which does cover a lot of the same features.

**Comment by hildjj** [comment]
I think that's mostly a packaging issue then.  I'll look into it.

**Comment by hildjj** [comment]
I've taken a first pass at this, and am interested in opinions before I merge it:

https://hildjj.github.io/quence/
