### ISSUE TITLE
Release planning: 2.0

### ISSUE THREAD

**Issue by hildjj** [hildjj/quence#41]
- [x] fix #21
- [x] fix #36
- [x] fix #40
- [x]  double-check `npm pack --dry-run`
- [x] `npm version major`, make sure new version stuff works.  Look for other places the old version number might be
- [x] publish

**Comment by hildjj** [comment]
@ekr do you want any other features before a release?

**Comment by ekr** [comment]
No, I think we're good for now.

**Comment by hildjj** [comment]
Published.
